### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pierreozoux** [teemow/prometheus-borg-exporter#4]
Thanks for the code,

Is it intentional to keep the code proprietary, or is it just that you forgot to put a license?

I'd like to reuse your code, but just want to make sure that the license is some kind of open source!

Thanks :)

**Comment by C-Duv** [comment]
Looks like afa87e9dfb111d83421f538c323db4a5c912b001 fixed this issue by adding a `LICENCE` file for Apache Licence 2.0.
